2012-03-24 21:40:20,663 - ubuntuone.SyncDaemon.Main - INFO - Starting Ubuntu One client version 2.0.0
2012-03-24 21:40:20,663 - ubuntuone.SyncDaemon.Main - INFO - Using '/home/saratt/Ubuntu One' as root dir
2012-03-24 21:40:20,664 - ubuntuone.SyncDaemon.Main - INFO - Using '/home/saratt/.local/share/ubuntuone/syncdaemon' as data dir
2012-03-24 21:40:20,664 - ubuntuone.SyncDaemon.Main - INFO - Using '/home/saratt/.local/share/ubuntuone/shares' as shares root dir
2012-03-24 21:40:20,664 - ubuntuone.SyncDaemon.tritcask - INFO - Initializing Tritcask on: /home/saratt/.local/share/ubuntuone/syncdaemon/tritcask
2012-03-24 21:40:20,682 - ubuntuone.SyncDaemon.tritcask - INFO - found 1 data files, 0 dead and 0 broken files
2012-03-24 21:40:20,695 - ubuntuone.SyncDaemon.tritcask - INFO - keydir ready! (keys: 2)
2012-03-24 21:40:20,730 - ubuntuone.SyncDaemon.fsm - INFO - loading updated metadata
2012-03-24 21:40:20,731 - ubuntuone.SyncDaemon.fsm - INFO - initialized: idx_path: 1, idx_node_id: 0, shares: 1
2012-03-24 21:40:20,733 - ubuntuone.SyncDaemon.filesystem_notifications.GeneralProcessor - INFO - Ignoring files: ['\\A#.*\\Z', '\\A.*~\\Z', '\\A.*\\.py[oc]\\Z', '\\A.*\\.sw[nopx]\\Z', '\\A.*\\.swpx\\Z', '\\A\\..*\\.tmp\\Z', '\\A\\.~lock\\..*#\\Z']
2012-03-24 21:40:20,739 - ubuntuone.SyncDaemon.HQ - INFO - HashQueue: _hasher started
2012-03-24 21:40:22,115 - ubuntuone.SyncDaemon.DBus - INFO - DBusInterface initialized.
2012-03-24 21:40:22,116 - ubuntuone.SyncDaemon.DBus - INFO - connect was requested. Are we autoconnecting? True.
2012-03-24 21:40:22,252 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'INIT'  (queues IDLE  connection 'Not User Not Network')>; queue: 0; hash: 0) ----
2012-03-24 21:40:22,253 - ubuntuone.SyncDaemon.Main - NOTE - Local rescan starting...
2012-03-24 21:40:22,254 - ubuntuone.SyncDaemon.local_rescan - INFO - start scan all volumes
2012-03-24 21:40:22,270 - ubuntuone.SyncDaemon.local_rescan - INFO - processing trash
2012-03-24 21:40:22,270 - ubuntuone.SyncDaemon.local_rescan - INFO - processing move limbo
2012-03-24 21:40:22,272 - ubuntuone.SyncDaemon.local_rescan - INFO - Ignoring path as it's a symlink: '/home/saratt/Ubuntu One/Shared With Me'
2012-03-24 21:40:22,274 - ubuntuone.SyncDaemon.Main - NOTE - Local rescan finished!
2012-03-24 21:40:22,274 - ubuntuone.SyncDaemon.Main - INFO - hash queue empty. We are ready!
2012-03-24 21:40:23,944 - ubuntuone.SyncDaemon.DBus - WARNING - 'CredentialsNotFound': () {'member': 'CredentialsNotFound'}
2012-03-24 21:40:23,945 - twisted - ERROR - Unhandled error in Deferred:
2012-03-24 21:40:23,946 - twisted - ERROR - Unhandled Error
Traceback (most recent call last):
Failure: ubuntuone.platform.linux.dbus_interface.NoAccessToken: CredentialsNotFound

2012-03-24 21:42:22,252 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; hash: 0) ----
2012-03-24 21:44:22,252 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; hash: 0) ----
2012-03-24 21:46:22,253 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; hash: 0) ----
2012-03-24 21:48:22,253 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; hash: 0) ----
2012-03-24 21:50:22,253 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; hash: 0) ----
2012-03-24 21:52:22,252 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; hash: 0) ----
2012-03-24 21:54:22,253 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; hash: 0) ----
